ci/start-db.sh
60 seconds might be a bit long, but automatic releases do fail because of this timing issue with the db not being up reliably after 30
=> fix(CI): need to wait longer for DB to be available

.travis.yml, components/app.js, readme.md, spec/tests/app.js, xquery/install-package.xq, xquery/remove-package.xq
A real breakthrough. Finally XAR installation is stable.
=> feat: stable XAR upload and install

spec/examples/exist-ls
Cleaner separation of concerns:
- The XQuery that is sent to the server uses a variable $collection
which is declared as external.
- The call to db.queries.readAll provides the value for this variable.
=> doc: improve exist-ls example script

components/app.js, readme.md, spec/tests/app.js, xquery/install-package.xq, xquery/remove-package.xq
Read the package URI from the XAR package that is installed.
Since not removing a package with the same URI, before installation leads to severe issues with an existdb instance this will help mitigate them, as the user does not have to know the package URI.
Additionally, dependencies are resolved using HTTPS by default.
BREAKING CHANGE:
The signature of the function `db.app.install` changes, as the packageUri parameter is no longer needed.
=> Improve package installation

.github/actions/setup-existdb/action.yml, .github/workflows/release.yml, .github/workflows/test.yml
- re-use setup-existdb action in both test and release definitions
- add OS to matrix but limit to ubuntu for now
- release job depends on test now
=> chore(ci): improve github actions setup

components/connection.js, package.json, readme.md, spec/tests/readenv.js
An empty password set in ENV would cause the basic_auth not to be returned by readOptionsFromEnv
It's also tested now :)
=> Fix: readOptionsFromEnv

package-lock.json, package.json, spec/examples/exist-tree, spec/examples/readme.md
This new command line tool allows you to list the contents of any 
collection in your database as a tree.
The option `-l` or `--level` controls how many levels down the tree will
traverse.
Example:
```bash
spec/examples/exist-tree --level 2 /db
```
On a fresh existdb instance this will output:
```
db
├─ system
│  ├─ config
│  ├─ security
│  ├─ plugins
│  └─ repo
└─ apps
├─ packageservice
├─ dashboard
├─ eXide
├─ doc
├─ fundocs
└─ monex
```
=> Add CLI tool exist-tree

spec/examples/exist-ls
This PR introduces new flags and extended capability to the existing CLI tool `exist-ls`
- `--extended`,`-l`: output mode, owner, group, mtime in addtition to
the name
- `--glob`, `-g` filter list to only include items that match the given
glob-pattern. Only * and ? are supported at the moment
- `--color`, `-G` color the output
Example
```bash
$ spec/examples/exist-ls -l /db
rwxr-xr-x SYSTEM dba    0 25 Jan 16:49 system
rwxr-xr-x SYSTEM dba    0 25 Jan 16:49 apps
```
=> feat(examples): exist-ls roughly mimics the ls command

components/collections.js, readme.md, spec/tests/collections.js
Implements a call to collectionExistsAndCanOpen function
provided by the XML RPC API of existdb.
It will
- return `true` if the collection exists and the current user can open it
- return `false` if the collection does not exist
- **throws** an exception if the collection exists
but the current user cannot access it
=> feat(collections): existsAndCanOpen

spec/examples/exist-ls
Older elements will display the year instead of the time they were last
modified.
In order for the year to be padded appropriately it is now converted to
a string.
=> fix(examples): render padded year in exist-ls extended

spec/examples/exist-install
- now also displays `updated` when a previous installation was found
- improved _and fixed_ display of hostname, now displays server URL with
protocol and non-standard port
=> fix(examples): exist-install working again

package-lock.json, package.json, spec/examples/exist-exec, spec/examples/exist-install, spec/examples/exist-ls, spec/examples/exist-tree, spec/examples/exist-upload, spec/examples/readme.md
Supports reading queries from the command line or from a file (with `-f`).
Variables can be bound using the `-b` parameter.
The the path to the query file, the bound variables and even the query string can be read from standard input by using `-`. 
closes #206
```
exist-exec
Execute queries in an exist-db
Usage:
exist-exec [options] [query]
Options:
--version  Show version number                                   [boolean]
-f, --file     Read query File (pass - to read from standard input)
-b, --bind     Bind variables (either as JSON string or - to read from
standard input)                            [default: (default)]
-h, --help     Show help                                             [boolean]
```
```bash
spec/examples/exist-exec '1 to 9'
```
**Output**
```bash
1,2,3,4,5,6,7,8,9
``` …
=> feat(examples): first implementation of exist-exec

.github/workflows/semantic-release.yml, components/app.js, readme.md, spec/tests/app.js, spec/tests/collections.js, spec/tests/users.js
Mount autodeploy folder in the docker image to something that does not include a single XAR (here, I used the xquery folder).
This together with some tweaks to the health check speeds up the CI runs to just about a minute from 1:45 
That is almost half the time.
Many thanks to @duncdrum and his knowledge of docker and GHA, for pointing me in the right direction.
Some interesting findings: 
- the collection `/db/system/repo` is not present when not a single package was installed.
To adapt to that `db.app` now checks for a temporary collection `/db/pkgtmp` and creates it if it does not exist.
Is the current user not allowed to open that collection (as guest might not be able to) the installation fails.
But it would fail in any case later on as guest is not allowed to install packages.
- the …
=> feat: run tests against an instance without bundled packages 

spec/examples/exist-ls
fixes #233
Change time formatting to not use timeStyle which is only available if a system has full-icu installed.
This dependency was implicit and is also not used anywhere else.
=> fix: drop implicit dependency on full-icu

components/queries.js, index.js, readme.md
Allows importing node-exist within an ES module
```js
import {connect} from '@existdb/node-exist'
```
=> fix: import in module (esm)

.npmignore, package.json, readme.md, spec/examples/readme.md
BREAKING CHANGE: Installing this package globally does not expose the
command line examples anymore as the entire spec folder is now excluded.
Please have a look at [xst](https://github.com/line-o/xst) for a command
line client to interact with existdb instances.
=> chore(examples): exclude spec folder from release

package-lock.json, package.json
- `nom test` calls standard with fix flag
- dependencies that are only declared in examples are now moved to devDependencies which decreases released package size
=> Two small developer life improvements

.github/workflows/semantic-release.yml, components/connection.js, components/documents.js, components/rest.js, components/util.js, index.js, package-lock.json, package.json, readme.md, spec/connection.js, spec/examples/exist-upload, spec/examples/rest.mjs, spec/tests/app.js, spec/tests/collections.js, spec/tests/documents.js, spec/tests/index.js, spec/tests/queries.js, spec/tests/resources.js, spec/tests/rest.js, spec/tests/users.js
node-exist exports a new async function `getRestClient` accepting the
same connection options as connect did.
The returned client has three methods `get`, `post`, `put` and `del` to
interact with eXist-db using the [REST-API](https://exist-db.org/exist/apps/doc/devguide_rest)
```
const { getRestClient } = require('../../index')
const rc = await getRestClient(connectionOptions)
await rc.put('<root />', '/db/test.xml')
await rc.get('/db/test.xml')
await rc.post('/db', query, options)
await rc.del('/db/test.xml')
```
see [example/rest.mjs](https://github.com/eXist-db/node-exist/pull/243/files#diff-3a44cd83eda759197802110e8a6dcf7c828edf223c78dc63421217a154384511) for a runnable version of above code
=> implement eXistdb REST-api client

.github/workflows/semantic-release.yml, components/connection.js, spec/tests/rest.js
The protocol _must_ end with a colon. This lead to the prefixUrl to contain a double colon (`::`), also known as Paamayim Nekudotayim.
For the tests with the protocol set to `http:` the other port (8080) is now exposed in the container in the CI test setup.
=> fix(restClient): protocol in connectionOptions

.github/dependabot.yml, .github/workflows/semantic-release.yml, package.json, spec/tests/documents.js, spec/tests/rest.js
`npm test` checks:
- if coding style is adhered and will error now if any problems occur
- if a test is marked as `.only` the tests will not run but fail instead
`npm run lint` will check coding style and automatically fix any problem that can be auto-fixed
Mark exist-db v7.0.0-SNAPSHOT (`latest` image) as experimental as it obviously has an issue resulting in two test reproducibly failing.
Change test-matrix to only test on node versions 16, 18, 20 (dropping 14 which has reached EOL).
Add GitHub-actions to dependot configuration.
=> Improve and adapt tests and npm scripts

components/documents.js, components/queries.js, readme.md, spec/tests/documents.js, spec/tests/queries.js
This fixes some hard to understand errors when utilising some node-exist functions:
```
Error: XML-RPC fault: No method matching arguments: java.lang.String, java.lang.String
```
=> options default to empty Objects
